/*
 * FizzBuzz Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DefaultResponse struct {
	Status int32 `json:"status"`

	Message string `json:"message"`
}

// AssertDefaultResponseRequired checks if the required fields are not zero-ed
func AssertDefaultResponseRequired(obj DefaultResponse) error {
	elements := map[string]interface{}{
		"status":  obj.Status,
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseDefaultResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DefaultResponse (e.g. [][]DefaultResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDefaultResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDefaultResponse, ok := obj.(DefaultResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDefaultResponseRequired(aDefaultResponse)
	})
}
