/*
 * FizzBuzz Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FizzbuzzPostRequest struct {

	// A count number to get FizzBuzz message
	Count int32 `json:"count,omitempty"`
}

// AssertFizzbuzzPostRequestRequired checks if the required fields are not zero-ed
func AssertFizzbuzzPostRequestRequired(obj FizzbuzzPostRequest) error {
	return nil
}

// AssertRecurseFizzbuzzPostRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of FizzbuzzPostRequest (e.g. [][]FizzbuzzPostRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFizzbuzzPostRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFizzbuzzPostRequest, ok := obj.(FizzbuzzPostRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFizzbuzzPostRequestRequired(aFizzbuzzPostRequest)
	})
}
